59-implement-all-clients-endpoints
aanndryyyy/e-financials-php-client pull request #61
Opened 2023-04-03 17:47 UTC by kaarelkaarelson

2023-04-07 07:14 UTC, aanndryyyy requested changes
I have currently not tested it against the real API, but will do it soon when more endpoints are done.

2023-04-07 07:14 UTC, aanndryyyy commented on src/API/Clients.php
> +                'internal_error' => "Missing required parameter(s): $missingKeys",
@kaarelkaarelson Using `throw` consistently in the PHP client for errors would mean that the developer, who is using this client in the future will need to have a `try catch` block around the code when using our client. Otherwise, they would need to check the returned array contents every time - and we can accidentally be inconsistent with the error keys. I was not considering this when we started coding but now it seems the logical solution. The way you have implemented it here is not wrong and is quite a common way of handling it.

So I suggest throwing standard, and even custom, exceptions in case of unexpected results in the PHP client. In this case, `InvalidArgumentException` is sufficient.

https://www.php.net/manual/en/class.invalidargumentexception.php
https://www.php.net/manual/en/language.exceptions.extending.php

2023-04-07 09:50 UTC, kaarelkaarelson commented on src/API/Clients.php
> +                'internal_error' => "Missing required parameter(s): $missingKeys",
Thanks for clarification. I refactored my code to throw `InvalidArgumentException` error.

2023-04-13 07:08 UTC, aanndryyyy approved these changes
All is good!

2023-04-13 07:15 UTC, merged