Implement invoice endpoints
aanndryyyy/e-financials-php-client pull request #69
Opened 2023-04-06 12:13 UTC by kaarelkaarelson

All invoice endpoints done.

2023-04-07 07:06 UTC, aanndryyyy requested changes
PHPStan pass is the only problem I see at the moment. I will test run the endpoints at some future time.

2023-04-07 07:06 UTC, aanndryyyy commented on src/API/Invoices.php
> +     * @param array<string,mixed>|array{
This new line seems to mess up PHPStan, not passing.

2023-04-07 07:06 UTC, aanndryyyy commented on src/API/Invoices.php
> +            throw new \InvalidArgumentException(
Let's keep using `throw` for errors inside the API Client. Then it is easy to use a `try catch` block when using the Client in PHP solutions.

2023-04-07 09:59 UTC, kaarelkaarelson commented on src/API/Invoices.php
> +     * @param array<string,mixed>|array{
Correct, empty comment line was causing the problem

2023-04-07 10:01 UTC, kaarelkaarelson commented
@aanndryyyy Resolved the issue. Please review again.

2023-04-13 07:07 UTC, aanndryyyy approved these changes
All is good!

2023-04-13 07:15 UTC, merged